var GAME_LEVELS = [
    [
        "                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                  x                                             ",
        "                                 xvx                             xxxxx          ",
        "                                                                 xx!xx          ",
        "                                                                 x!!!x          ",
        "                                                                 xx!xx          ",
        "                                                                  xvx           ",
        "                                                                                ",
        "                                                                                ",
        "   x                      o o                                                   ",
        "   x                                                                            ",
        "   x          o        xxxxxxxxxxx                                              ",
        "   x @     d      xxxxxx     x!         d    o                 xxx o x          ",
        "   xxxxxxxxxxxxxxxx          x!      xxxxxxx                 xxxxx o x          ",
        "                             x!    o !x    xxxx         o        x o x          ",
        "  x                          x!      !x                          x o x          ",
        "                             x!    xxxx                          x o x          ",
        "                             x!      !x          xx    xxxx      x o xxxxx      ",
        "                             x!      !x                          x o     x      ",
        "                             x!      !x           oooo         xxx     o x      ",
        "                             x!      !x                     xxxxxx       x      ",
        "xxxx                         xxxxx   !x       xxxxxxxxxxxxxxx    x       x      ",
        "                             x! o    !x       !!!!!!!!!!!!!!!    xxxxxxxxx      ",
        "                             x!      !x                                         ",
        "                             x!      !x                                         ",
        "                             x!      !x                                         ",
        "                             x!      !x                                         ",
        "                             xxxxxxxxxx                                         "
    ],
    [
        "                                                                                                                   ",
        "                                                                                                                   ",
        "                                                                                                                   ",
        "                                                                                                                   ",
        "                                                                                                                   ",
        "                                                                                                                   ",
        "                                                                                                                   ",
        "                                                                                                                   ",
        "                                                                                                                   ",
        "                                               x                                                                   ",
        "                                              xvx                                            t                     ",
        "                                                                                                  d                ",
        "  @                                                                     t                   xxxxxxx                ",
        "xxxxxxxxxxxxxxxxxxxxx                                                d                            x                ",
        "                     xx                                           xxxxx!!!!         xxx           x                ",
        "                       xx     t t     t t        t          xxx                                   x                ",
        "                         xx        d                  xxx                                         x                ",
        "                           xxxxxxxxxxxxxxxxxx   xxx                           xxxx   t            x  t             ",
        "                                                                                         d        x                ",
        "                                              !!!!!!!!!!!!!!!!!!!!!!!!!!!!          xxxxxxxxx     xxxxxxx          ",
        "                                                                                                                   ",
        "                                                                                                                   ",
        "                                                                                                                   ",
        "                                                                                                                   "
    ],
    [
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                         xxx     xxx                                                                           ",
        "                                                         x!x     x!x                                                                           ",
        "                                                         xvx     xvx                                                                           ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                 e e                                           ",
        "                                                                                                                                               ",
        "                                            e     xxxxx                                  e      xxxxx                                          ",
        "                                                      x                                             x                                          ",
        "                e                   e     xxxxx       x       e                 e      xxxxx        x                                          ",
        "                          d                           x                d                            x                                          ",
        "              xxxxx     xxxxx     xxxxx               x     xxxxx    xxxxx    xxxxx                 x   e           e           e              ",
        "   @                                                  x                                             x         d             d                  ",
        " xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               ",
        "                                                                                                                                               "
    ]
];

if (typeof module != "undefined" && module.exports)
    module.exports = GAME_LEVELS;